### ISSUE TITLE
Use environment variables in flags

### ISSUE THREAD

**Issue by niosus** [niosus/EasyClangComplete#128]
Reported by @simonhaenisch
> Is there a way to use environment variables in include directives? I tried something like
> `-I%LIB_DIR%\\include`

**Comment by niosus** [comment]
No, currently not possible. But sounds like a nice thing to have.

**Comment by rchl** [comment]
Just a note that on Mac exceptionally difficult to define environment variables that would be picked up by GUI apps like sublime. At least I have pretty much failed with latest macOS'. So I think it wouldn't be much useful on Mac.

**Comment by niosus** [comment]
Really? Is is not like defining them in `.bashrc`? Like on other unix systems?

**Comment by rchl** [comment]
That will only work for shell (terminal), I'm pretty sure.

**Comment by simonhaenisch** [comment]
But doesn't run ECC a shell command for `clang++`? Then the environment variables should be available there. They are accessible in Python via `os.environ.get()`, so ST should have access to them via the python interpreter.

**Comment by rchl** [comment]
Hmm, you are right. With shell=True in subprocess call it should be OK.

**Comment by rchl** [comment]
But then this bug talks about handling environment variables in include paths which doesn't involve subprocess calls. So for this case the sublime's python environment would have to see those variables itself. And I'm fairly sure that Sublime (or any other GUI app) doesn't inherit variables from .bashrc. Let me check quickly...

**Comment by rchl** [comment]
Yep, doesn't work:
```
% cat ~/.bashrc
export TEST_VARIABLE=1
```
Then in Sublime console:
```
import os; os.environ
```
And there is no sign of TEST_VARIABLE.

I've also tried restarting OS for good measure.
This was tested on MacOS Sierra

**Comment by simonhaenisch** [comment]
I see, it's very different to environment variables in Windows. I didn't use environment variables a lot on Mac/Unix (besides `EDITOR` and `TERM`), but they really are a helpful thing for developing on Windows, because Windows messed it up :P Also they are really annoying to use... I guess we can close this, because it doesn't really have a benefit. Who moves an installed lib anyway.

If you'd want to make it for Windows, you could probably use a simple regex like

```js
/%([^%]+)%/g
```

and do a string replace of `%$1%` with `os.environ.get($1)` (for each match).

In Windows, `%` is not allowed in file names, so this should be safe.

**Comment by niosus** [comment]
Actually, I really don't see what stops us from using `os.path.expandvars(path)` :)
