### ISSUE TITLE
/bin/sh: cmake: command not found

### ISSUE THREAD

**Issue by cubuspl42** [niosus/EasyClangComplete#145]
EasyClangComplete can't find my `cmake`. It's `/usr/local/bin/cmake`; installed via Homebrew. I guess that the root cause is that `/usr/local/bin` is not in `PATH` for Cocoa GUI apps. Using Homebrew for many people is **the** way of installing software, so it would be cool if it was supported by default.

OS X 10.11.6 (15G1108)

**Comment by niosus** [comment]
hm, is there any particular reason why you don't want to add folders `/usr/local/*` to `PATH`?

Anyway, if that's needed, I could add a setting for a cmake binary, that would default to cmake.

**Comment by rchl** [comment]
As I've mentioned in some other issue, it's close to impossible to modify PATH for GUI applications on OSX (since some recent OSX release).
There is a workaround for Sublime that probably every mac user should have - https://github.com/int3h/SublimeFixMacPath (haven't tested it myself).

**Comment by cubuspl42** [comment]
@niosus
OS X doesn't read PATH that I set in my `.zshenv` (why should it?). I think that explicit check for `/usr/local/bin/cmake` would be desired on OS X... It's already _extremely_ complicated to set up C++ completion, so something working something out of the box would be desired...

**Comment by niosus** [comment]
Ok, so clearly we need a way to configure cmake path. The only thing unclear to me is if we need a generic way of setting a cmake binary or there is exactly one workaround that we need to apply on exactly one system?

I would be in favor of a workaround as it allows to run everything out of the box, and not force the user to go into the settings as the first thing that he does with the plugin.

**Comment by jdumas** [comment]
I think the "standard" fix would be to install this `SublimeFixMacPath` on Mac OS, since you probably need it for other plugins anyway (and I mean you should rely on `PATH` as a way to find applications by default, it shouldn't be your job to guess what's going on on every system). Then it probably doesn't hurt to add a `path_to_cmake_executable` configuration option, empty by default. And those who don't want to install the other plugin, or put cmake in a non-standard location, can have at it.

If you add the option `additional_path_items` to you plugin, containing by default `["/usr/local/bin"]`, you're basically making the same job as the `SublimeFixMacPath` plugin, which seems a bit redundant to me.

**Comment by david9991** [comment]
@niosus I am afraid not only to config the CMake Binary Path but also custom CMake Flags. e.g. I have modify the  `_CMAKE_MASK = '/usr/local/bin/cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DBREW_HOME=/usr/local -DSDK_HOME=/Users/David/SDK "{path}"'` , because we installed cmake via Homebrew (to /usr/local/bin) and make BREW_HOME and SDK_HOME point to the path where we need to use when compile in a CI environment.

**Comment by niosus** [comment]
Guys, I really cannot add much to this discussion. Are these variables that you propose standard? Does everyone use them if installing cmake from brew? Maybe somebody can come up with an initial PR and then we would discuss how to make it generic and easily accessible for the user in the discussions of that PR? It would be hard for me to implement that myself without having any experience with mac-specific issues.

**Comment by niosus** [comment]
After some time, I assume that the interest in this has dropped. It seems to me, that the original issue is solved by installing [SublimeFixMacPath](https://github.com/int3h/SublimeFixMacPath) and the CMake flags can be set via project-specific settings in the plugin. I will close this issue for now.
