### ISSUE TITLE
Completer is re-created on post-save

### ISSUE THREAD

**Issue by rchl** [niosus/EasyClangComplete#165]
I haven't analyzed it well but I think the completer for the view is needlessly re-created on saving a view.

This is the the stack trace when this happens:

```
  File "C:\Programy\Sublime\sublime_plugin.py", line 480, in on_post_save_async
    callback.on_post_save_async(v)
  File "C:\Programy\Sublime\Data\Packages\EasyClangComplete\EasyClangComplete.py", line 151, in on_post_save_async
    self.view_config_manager.load_for_view(view, settings)
  File "C:\Programy\Sublime\Data\Packages\EasyClangComplete\plugin\view_config.py", line 342, in load_for_view
    res = self._cache[v_id].update_if_needed(view, settings)
  File "C:\Programy\Sublime\Data\Packages\EasyClangComplete\plugin\view_config.py", line 86, in update_if_needed
    self.completer.update(view, settings.errors_on_save)
```
Seems like update_if_needed() will just create new completer. Even if there was one already.

**Comment by rchl** [comment]
Same code triggers from `on_activated_async` event.

After adding `print('INIT NEW COMPLETER')` in BaseCompleter.__init__ I see two new completers being created on view activation or save.

**Comment by rchl** [comment]
I see that this is how it works and maybe it's not a problem. I've noticed that due to some change of mine, but I need to figure out if there is actually any problem here.

**Comment by niosus** [comment]
Thanks for reporting.

There is an issue that I have seen quite a lot that `on_activated_async` is called multiple times by some weird reason. Maybe it has something to do with it.

Generating a new completer is ok and is really cheap, as soon as it is not the one being used. The code is probably not optimal, but that was the best way I could think of at that time. The reason is that we need to check many things like if we are using libclang or if it is available. This is then encapsulated in the creation of the completer. It will still not be used if `needs_update` does not decide otherwise.

**Comment by niosus** [comment]
> I see that this is how it works and maybe it's not a problem. I've noticed that due to some change of mine, but I need to figure out if there is actually any problem here.

I will close this for now, we can continue discussion of course. Also feel free to reopen if needed.
