### ISSUE TITLE
stl header can't work in win7 mingw platform

### ISSUE THREAD

**Issue by johnnyleeRH** [niosus/EasyClangComplete#265]
now I use st3 in win7, after I add the mingw stl path to the 'common_flags' parameter, such as 
  "common_flags" : [
    "-IC:\\Program Files (x86)\\mingw-w64\\i686-7.1.0-posix-dwarf-rt_v5-rev0\\mingw32\\i686-w64-mingw32\\include",
    "-IC:\\Program Files (x86)\\mingw-w64\\i686-7.1.0-posix-dwarf-rt_v5-rev0\\mingw32\\i686-w64-mingw32\\include\\sys",
    "-IC:\\Program Files (x86)\\mingw-w64\\i686-7.1.0-posix-dwarf-rt_v5-rev0\\mingw32\\lib\\gcc\\i686-w64-mingw32\\7.1.0\\include\\c++\\",
  ],
the vector method can't work, but the method in the above two path can work well. and even more, after I add the gcc c++ path, the  paths defined in my local .clang_complete file can't work, looks like something conflict.
Would you please give me some advise?

**Comment by niosus** [comment]
Unfortunately it is hard for me to help here as I am not a huge MinGW expert and it is hard to tell you what you are doing wrong in your own project. If you create a minimal verifiable example that I can run on my Windows 10 I can have a look into that if I find time. Otherwise, I will need to be just good at guessing, which I am not.

**Comment by johnnyleeRH** [comment]
Yes, It can't descript clearly by little words，anyway， I've already benefited from this plug-in.
Thanks a lot.

**Comment by niosus** [comment]
No problem. If you find a way to solve your problem and could tell me what can I do to ease up setup on MinGW - feel free. I will be happy to improve!
