### ISSUE TITLE
ERROR:EasyClangComplete.plugin.tools: view has wrong syntax: JavaScript

### ISSUE THREAD

**Issue by AnthonyWC** [niosus/EasyClangComplete#279]
From sublime 3 console I see

`ERROR:EasyClangComplete.plugin.tools: view has wrong syntax: JavaScript`

when editing a javascript file.  Why is it even active for .js?

**Comment by niosus** [comment]
This is a valid point. I guess the reason is that sublime's api will call all active plugins. If you know how I can enable my plugin to be called only for specific syntax, I would much appreciate the input. 

In any case, it doesn't make sense to show the message as an error, it should be a debug message instead.
