### ISSUE TITLE
Doesn't parse default arguments values

### ISSUE THREAD

**Issue by strexicious** [niosus/EasyClangComplete#312]
- Sublime Text version: `3`
- which system are you on: `Windows 10`

You can find the repo [here](https://github.com/strexicious/Gryfe) or you can take a look at the image below.

![image](https://user-images.githubusercontent.com/13009365/30004387-93fbd4a8-90ce-11e7-8b37-2eee421676ee.png)

**Comment by niosus** [comment]
This is likely caused by something else. There might be some error in another included file that we don't see here that causes all the subsequent errors to be just garbage. There is no way currently to display all the errors in all files, but you can switch to `"use_libclang": false` and enabling verbose output you will be able to see the actual clang command in the console. It starts with `clang` in the output. If you copy this to your powershell it should be able to provide you the real compilation output, where the first error is what you are after.

**Comment by strexicious** [comment]
The error was indeed coming from included files. I was missing some of the include directories required by `iostream`. Now I have included a bunch of more directories and the plugin is working fine now.

But clang errors and warnings have only increased since I'm using MSVC. It doesn't output those errors unless I have `verbose: true`. So I guess it should't be much of a problem.

Note: I'm only using clang for this plugin. For building the code I use CMake  with `-G " Visual Studio 15 2017"`.

**Comment by niosus** [comment]
Yeah, these errors will appear as there is a difference between the subsets of c++ implemented by different folks. I'm not really fluent in Windows and how the development goes there, but it seems these errors will stick for some time.
