### ISSUE TITLE
No Autocomplete of STL in Ubuntu

### ISSUE THREAD

**Issue by rshanor** [niosus/EasyClangComplete#315]
Trying to use in Ubuntu and running into some issues.  Typing in "vec" will let me autocomplete vector, but after creating the vector, things like v.size wont auto complete. String and vector is recognized as part of STL when included.

Thanks!

**Comment by niosus** [comment]
Hey @rshanor this is really weird as this functionality is covered by unit tests. It seems that you chose not to follow the issue template I have set up for this repo which strips me from additional information about what exactly is happening. Can you please revise your issue following that instruction? Most importantly, I would love to see the log of what is happening, otherwise my guess is as good as yours.

**Comment by niosus** [comment]
I have just updated my ubuntu installation and it seems that it is now possible to install clang 6.0 in it (what?)

The plugin was not handling it well. So I have added the full support for clang 5.0 and a fallback support for 6.0. It will be available in the next release.

**Comment by niosus** [comment]
I have just pushed the new release. Please reopen this issue if you still see this behavior after the plugin updates.

**Comment by rshanor** [comment]
Thanks @niosus, and sorry about the incorrectly formatted issue.
