### ISSUE TITLE
The requested operation cannot be performed on a file with a user-mapped section open.

### ISSUE THREAD

**Issue by RootKiller** [niosus/EasyClangComplete#321]
Hello I have problem - and I'm always able to reproduce it. If you have single file that is bigger than hello world example (https://github.com/EpicGames/UnrealEngine/blob/release/Engine/Source/Developer/BlueprintProfiler/Private/BlueprintProfiler.cpp <- used this one to reproduce) make sure there are some error like missing symbols etc (i just setup single .cpp file) then try to save it relatively quickly then you get error I mentioned in the title.

I think it's some timing issue between saving file and opening it by clang to compile.

Log:
https://gist.github.com/RootKiller/0ab780079f1b85761c5c23fa56b5f60b

Version:
- Sublime Text version: `3.0, Build 3143`
- which system are you on: `Windows 10 HP 64bit`

**Comment by niosus** [comment]
Oh wow. This is new to me and looks pretty weird :)
Do you know what causes this line of your log? Is this sublime text or do you have other plugins?
```
error: Unable to save D:\work\test_project\test_project\main.cpp
```
I will try to reproduce this, but it will take a while as the next two weeks I am completely off the grid.

**Comment by RootKiller** [comment]
This is the list of installed package on my work PC. At home I have pretty much the same set of packages and I was also able to reproduce it there.

```
EasyDiff
JSON Reindent
Markdown HTML Preview
Markdown Preview
Package Control
Predawn
Theme - Asphalt
Theme - itg.flat
TrailingSpaces
```

I'm pretty sure this log line is from sublime when it tries to save the file. I may try to debug it on my own and give you more details like system call log so we could see if there is file access race condition.

**Comment by niosus** [comment]
I googled around this issue a bit and it seems to happen quite often with different IDEs. I guess it is Windows' specialty too. We do pass the file into libclang to generate a translation unit. If libclang decides to lock the file and then sublime text tries to overwrite it while its locked we will get the conflict. I don't know the Windows mechanism for handling these things. Does the issue only happen when saving the file quickly?

**Comment by RootKiller** [comment]
Unfortunately after more tests I'm able to reproduce it with each save :/.

22.09.2017 5:42 PM "Igor Bogoslavskyi" <notifications@github.com>
napisał(a):

**Comment by niosus** [comment]
I love windows :) I will try to reproduce this and will search for a way to fix this. Is it too much to ask you to try a different clang version? Could you try clang 4.0 as that version worked pretty reliably? Just to try to nail down the possible cause.

**Comment by brupelo** [comment]
Oh, glad this issue is already opened, I can confirm this also happens to me on win7 & clang

    clang version 5.0.0 (tags/RELEASE_500/final)
    Target: x86_64-pc-windows-msvc
    Thread model: posix
    InstalledDir: C:\Program Files\LLVM\bin

For instance:

    [ECC:ERROR  ]: cmake has finished, but no compilation database.
    error: Unable to save C:\Users\KneDa\Desktop\t1m1-edx\FOSSSim\TwoDSceneXMLParser.cpp
    Error: The requested operation cannot be performed on a file with a user-mapped section open.
    [ECC:INFO   ]: init completer based on libclang
    [ECC:INFO   ]:  running command: cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON  "C:\Users\KneDa\Desktop\t1m1-edx"
    [ECC:INFO   ]: cmake produced output: 
    -- Configuring done
    -- Generating done
    -- Build files have been written to: C:/Users/KneDa/AppData/Local/Temp/EasyClangComplete/cmake_builds/4d5e14af037692664e6b30e1d823f760

    [ECC:ERROR  ]: cmake has finished, but no compilation database.
    [ECC:INFO   ]: init completer based on libclang
    [ECC:INFO   ]:  running command: cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON  "C:\Users\KneDa\Desktop\t1m1-edx"
    [ECC:INFO   ]: cmake produced output: 
    -- Configuring done
    -- Generating done
    -- Build files have been written to: C:/Users/KneDa/AppData/Local/Temp/EasyClangComplete/cmake_builds/4d5e14af037692664e6b30e1d823f760

    [ECC:ERROR  ]: cmake has finished, but no compilation database.

Also, it's worth to mention when i sent you my last [PR](https://github.com/niosus/EasyClangComplete/pull/330) and tried running the test suite, not all of them were passing. Not sure it's relevant to this issue but I'm sure is worth mentioning. When you try to reproduce this issue, make sure you use my PR, otherwise you'll get the subprocess error thing :)

Btw, isn't included windows on the CI system?

**Comment by brupelo** [comment]
@niosus Also, worth mentioning this is just not happening very rarely, it happens with all files containing errors, so i'd say this bug is **critical** as it makes the plugin basically unusable

**Comment by brupelo** [comment]
@niosus I've reverted back from clang5.0 to clang4.0.1 and the error dissapeared magically... Hopefully that can give you more clues about the current bug and how to solve it

**Comment by niosus** [comment]
Ok, it's good to know that it is clang version related. At least it gives me a slight hint. I will be looking into this, but don't really understand what causes this just yet.

**Comment by farhangj** [comment]
I had the same issue and reverting back to clang 4.0.1 fixed it.
Thanks for the post and looking into this, hopefully @niosus finds a fix with 5.0.

**Comment by mheinzler** [comment]
Hi guys,
after spending some hours on this I found out that libclang keeps an open file handle that prevents editing the file (even outside of Sublime Text), while the binaries seem to work.

I could finally trace it to the reparsing functionality and even come up with a dirty fix (see fe10185). So far it seems to work but I have no idea what the real problem is. Maybe this helps you find a better solution.

**Comment by daniele-niero** [comment]
Any news on this? it is really make impossible to work

**Comment by niosus** [comment]
Sorry, completely missed the dirty fix. I can add it on the weekend probably. But I have no idea on what is happening and how to fix this.

**Comment by SpeCter** [comment]
I'm using the quick fix right now which fixes the saving problem, but it seems to crash the plugin host from time to time.

**Comment by niosus** [comment]
I feel like the part where we pass the current state of the files should be enough as then libclang will not be trying to access the file stored on disk. I don't see how this can crash the plugin. Let me try to push the fix into the repo and then we'll try to find out if the crash still happens to reduce the number of variables at play. This will happen this weekend.

**Comment by User7711** [comment]
I just ran into this. Is there anything I or we can do to fix this?

I'm currently using c++17 so I need clang 5+. But, i'm in the luxury situation that I can reconfigure the code for c++14 - because i'm not excessively using c++17 features - and with that support earlier versions of clang.

Best Regards.

--

clang version 10.0.0
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin

Sublime Text Build 3211

![ss](https://user-images.githubusercontent.com/34722701/88768264-2038d700-d17b-11ea-9b18-3f44d44cde60.png)
