### ISSUE TITLE
C++ class name cannot be auto completed without global namespace.

### ISSUE THREAD

**Issue by david9991** [niosus/EasyClangComplete#335]
# Please do this before submitting: #
- [x] check for already solved issues
- [x] try restarting Sublime Text

# Please state the following: #
- Sublime Text version: 3.0 build 3143
- which system are you on: macOS High Sierra

# What I need to help you: #
C++ class name cannot be auto completed without global namespace, see animation below.

![untitled](https://user-images.githubusercontent.com/123219/31423772-233e3bb0-ae89-11e7-8331-a884bd277d90.gif)

**Comment by niosus** [comment]
This is weird. I will check if we filter this out by mistake. It might be the case. Thanks for reporting.

**Comment by david9991** [comment]
I found it occurs when `OM` as both a Namespace and Classname prefix. Seems Classname auto-completion was overwrite by Namespace auto-completion result.

**Comment by david9991** [comment]
<img width="573" alt="screen shot 2017-11-07 at 9 45 31 am" src="https://user-images.githubusercontent.com/123219/32473052-8de64a6c-c3a0-11e7-9060-bdb6705b0119.png">

**Comment by niosus** [comment]
The issue was that we filtered out type information for all triggers that are not `"::"`. This was added before we had `" "` as a trigger, so adding space and tab as triggers that are allowed for showing type information should fix this issue. I will close this as soon as the PR lands into master. Thanks again for reporting.
