### ISSUE TITLE
EasyClangComplete fill some extra settings into the user preferences.sublime-settings

### ISSUE THREAD

**Issue by r44083** [niosus/EasyClangComplete#42]
Hi, I have noticed that EasyClangComplete automatically adds few settings into the sublime user settings. When I try to remove this new section of settings - all ok, but when I start using EasyClangComplete - this section of settings came up into user settings again.
This behavior is unacceptable. Could you please fix this bug?

EasyClangComplete adds "auto_complete_triggers" section into the user settings:
```
	"auto_complete_triggers":
	[
		{
			"characters": "<",
			"selector": "text.html"
		},
		{
			"characters": ".>:",
			"selector": "source.c++, source.c - string - comment - constant.numeric"
		}
	],
```

This is my EasyClangComplete settings:
```
{
	"use_libclang" : false,
	"autocomplete_all" : true,
	"search_clang_complete_file": false,
	"errors_on_save": false,
}
```

**Comment by niosus** [comment]
This is not a bug, it's a feature to ease up setup. There is a setting to turn this off. Just set 
`"auto_set_sublime_triggers" : false`

In which way does it annoy you? I would like to avoid confusion and irritation for people like you but at the same time avoid asking new users to set the triggers manually (I have seen a bunch of people failing to see these triggers need to be set)

**Comment by r44083** [comment]
Я считаю что в пользовательские настройки не должны лезть плагины. Возможно есть другой способ задать эти триггеры.

**Comment by niosus** [comment]
Sorry, this conversation may be useful for future, so I will stick to English. 

There may be another way (like modifying syntax-specific settings). My thoughts were:
- if the user uses the plugin, he anyway needs to set the triggers, so why not doing it for him.
- it is on by default, because I wanted to take this step away from the configuration of the plugin.

I may add a popup window that would ask the user if he wants the triggers set automatically. I guess this will be a better behavior.

**Comment by niosus** [comment]
Will you be happy with a popup asking you about putting something into user settings?

**Comment by niosus** [comment]
From 7eee8898345693961fac4b0b1e0002121ad0b4fb on the plugin will ask you if it is allowed to mess with your settings.
