### ISSUE TITLE
Write a tutorial how to get the plugin running on Windows

### ISSUE THREAD

**Issue by c0nd3v** [niosus/EasyClangComplete#433]
As far as I'm concerned it seems too complicated to get this plugin working correctly in windows.

I currently have my CMakeLists.txt to compile for MSVC on Windows, and Clang on Linux. This plugin inherently works perfect on Linux. As I understand it, to get this plugin to correctly work on windows, I would have to switch the compiler to Clang + MinGW (Which I'd prefer to use MSVC). The reason that I'd have to use Clang + MinGW is because if my CMakeLists.txt is told to use MSVC as the compiler, then the compile_commands.json will have arguements like: 

/FI stdafx.h

which is obviously incompatible with clang (would need to be -include stdafx.h).

Is it possible to have a cmake project that uses MSVC as the compiler and successfully use EasyClangComplete? Am I confused?

**Comment by niosus** [comment]
Yeah, I am aware of the issue, however, I never work with Windows and know few to nothing about its build environments. Currently, plugin is unit tested to work with visual C++ on Windows. This means that out of the box when Visual studio is installed the plugin is usually able to find the correct headers for STL functions and so on. I don't know how much harder it is when CMake comes into play. It would be cool if anybody would post an easy guide for Windows, but I am unfortunately not the right person for this.

I will keep this issue handing for now. Maybe somebody would be willing to spend some time and have a guide on how to set things up. It should probably be done after #274 is closed.

**Comment by mclayton7** [comment]
@c0nd3v can you give some details about the project you’re trying to use EasyClangComplete with? I definitely understand the windows issues, as I use MSVC on windows as well. I’ve recently added support for CppProperties.json files (see [here](https://blogs.msdn.microsoft.com/vcblog/2016/10/05/bring-your-c-codebase-to-visual-studio-with-open-folder/) for more information). Those files are easier than a compile_commands.json to handle because EasyClangComplete can just parse the include paths. It also might be possible to extend the existing behavior to support cmake and MSVC on windows more easily. 

I’ll try to write up some stuff for windows and see if I can get an example cmake project up and going for testing.

**Comment by c0nd3v** [comment]
@mclayton7 I have two projects in my sublime-project. One is a library and one is an executable. The executable includes the library (.lib/.a) and in the source files of the executable, it includes the headers from the library. In both CMakeLists.txt (library and executable) I have platform specific code.

for example:

if(WIN32)
    set(CMAKE_CXX_COMPILER "....../cl.exe")
elseif(UNIX)
    set(CMAKE_CXX_COMPILER "...../clang++-5.0")
endif()

I use ninja to generate build files. Obviously Windows cannot parse compile_commands.json because its using MSVC commands (i.e. /FI stdafx.h). An alternative would be to use clang + MinGW to get EasyClangComplete to parse compile_commands.json correctly, but then I cant compile with MSVC. I dont like that. I want to use MSVC.

Thanks! :)

**Comment by mclayton7** [comment]
@c0nd3v would you be able to upload your ``compile_commands.json`` as a gist or attach it here? Even if it's a partial/edited one that would still be helpful. 

I think the  best approach would be to detect the ``cl.exe`` compiler and parse the commands correctly before passing them to ``libclang``. Since ``libclang`` really just needs defines and includes, it should work just fine.

I'm not sure if EasyClangComplete has this issue, but when I used vim and YouCompleteMe, I'd always run into the problem of working with a new file and not having a compile command generated for it yet. That's why I use ``CppProperties.json``. I'll look and see how easy it is to add a generator to ``cmake``.

**Comment by SpeCter** [comment]
One of the biggest problems is the fact that the clang binary for windows defaults to:
 _x86_64-pc-windows-msvc_ 
as a target because it won't use/search the mingw libraries at all by default.
Setting the target to:
_x86_64-w64-mingw32_ or _x86_64-w64-windows-gnu_ (both are the same)
will make clang be aware of mingw libraries and use them by default if it can find them.
The msys2 package uses the right target by default.

This is only relevant if you only want to use clang + mingw. But with mingw and clang correctly set up it works just as easy as on linux(for me at least).

**Comment by niosus** [comment]
Ok, so I seem to be able to compile everything without issues by installing `MinGW` from here: https://osdn.net/projects/mingw/releases/

I needed only to add additional flags to the common flags and everything was working including the STL support. The needed setting:
```json
"common_flags": [
    "-IC:\\MinGW\\lib\\gcc\\mingw32\\6.3.0\\include\\c++",
    "-IC:\\MinGW\\lib\\gcc\\mingw32\\6.3.0\\include\\c++\\mingw32"
],
```

**Comment by niosus** [comment]
Added the above lines to the documentation: https://niosus.github.io/EasyClangComplete/settings/#common_flags

I believe this closes the issue.
