### ISSUE TITLE
Why does the fix triggers dialog add a `text.html` trigger?

### ISSUE THREAD

**Issue by simonhaenisch** [niosus/EasyClangComplete#56]
This isn't really an issue, rather a question. On Windows, when I answer the dialog with _"Sure!"_, this is what is written into my user settings file:

```
"auto_complete_triggers":
[
	{
		"characters": "<",
		"selector": "text.html"
	},
	{
		"characters": ".>:",
		"selector": "source.c++, source.c - string - comment - constant.numeric"
	}
]
```

As I couldn't find this in the plugin code I assume that ST adds this by itself (don't know why this would be necessary).

BTW wouldn't it make sense to add the triggers to the syntax specific files for C and C++ rather than the main user settings? Would maybe be more sensible in the modular ST package way, but may be harder to find/configure for the user.

**Comment by niosus** [comment]
Yes, the HTML part comes already configured for sublime text. Basically, now it will write all the triggers it finds already defined to the user preferences.

I actually was thinking of putting the settings into the syntax specific files, but there are a couple downsides. 
- First: as you pointed out, it is harder to find
- Second: to which of them? Currently the plugin works with `C`, `C++`, `C Improved` and `C++11` syntaxes. Should I just put it into the one currently opened? That may cause confusion if the user uses multiple syntax definitions for different files (like `.cpp` uses one and `.h` the other). As a way to solve this to some degree, I could open the file that was edited by the plugin to show the user where the settings are. Also, I could add a context menu to open those files. But it still causes confusion. Maybe I could put the triggers to all syntax settings, I don't know.

So I would rather just put them into user settings actually. The problem here is that then the other triggers like html (I also have rust) appear. I cannot just remove them, because I don't know which ones of them come from the actual settings file. As an option, I could parse the settings file myself, but I also doesn't seem like the best solution ever.

I am open to any thoughts from your side and would love to make is intuitive for the user.

**Comment by simonhaenisch** [comment]
Alright I get that, who knows how many other `C/C++` plugins there are/will be with custom syntax. So syntax specific files aren't really an option. Parsing the settings file doesn't sound like a good plan either.

Isn't it possible to let the plugin set the triggers? I thought that ST parses settings in the order default -> plugins -> user. Then the triggers would be set without the need to configure anything, but a user could still overwrite them in his user or syntax specific settings.

**Comment by niosus** [comment]
Oh, that is actually a very good though and I haven't thought about it before! It seems like this is a nice solution. I have to check if this actually works, but if it does, this is the best method.

**Comment by simonhaenisch** [comment]
<http://docs.sublimetext.info/en/latest/extensibility/packages.html#merging-and-order-of-precedence>

I saw this a while ago, but I didn't really look into it... not sure about how this has to do with settings

**Comment by simonhaenisch** [comment]
Here we go for settings:

<http://docs.sublimetext.info/en/latest/customization/settings.html#order-of-precedence-of-sublime-settings-files>

**Comment by simonhaenisch** [comment]
So you can create a `Preferences.sublime-settings` file in `Packages/EasyClangComplete` and it will be merged into the default prefs, and then the user prefs file will be merged after that. Sounds like it is the way to go.

**Comment by niosus** [comment]
This actually looks pretty good and easy to try. Will do today.

**Comment by niosus** [comment]
Ok, it works as expected, big thanks! 
I will remove the dialog then as it is really not needed. I will also add an option to call with <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>P</kbd> to open the `Preferences.sublime-settings` file if anyone would want to edit these settings. + Documentation of course.

**Comment by niosus** [comment]
This should be fixed now. There are triggers in the package and it will not write anything to user preferences anymore.
