### ISSUE TITLE
Completion not available immediately after *

### ISSUE THREAD

**Issue by detly** [niosus/EasyClangComplete#597]
# System info

- Sublime Text version: `3207`
- Which system are you on: `Ubuntu 18.04.1`
- Clang version: `8.0.1`

# Minimal example

Start with this for `main.c`:

```c
#include "./some_constants.h"

int main(void)
{
    int h[];
}
```

Call this `some_constants.h` and save it in the same directory:

```c
#define SOME_CONSTANT (1U)
#define ANOTHER_CONSTANT (1U)
```

Position the cursor in between the `[]` and type `SOME_C` - it will prompt to autocomplete to `SOME_CONSTANT`. Type ` * ANOTH` and you get another autocomplete prompt for `ANOTHER_CONSTANT`. Type `*ANOTH` (no spaces) and there is no autocomplete prompt. Both are valid C.

Log attached: [ecclog.txt](https://github.com/niosus/EasyClangComplete/files/3093007/ecclog.txt)

Here's a picture (I type the question marks after trying `tab`, `ctrl+space` etc):

![ECC](https://user-images.githubusercontent.com/311239/56340708-0bd70200-61f6-11e9-98d5-ce7077cf6580.gif)
:

**Comment by niosus** [comment]
I will look into this. I guess it is because sublime does not distinguish star as a word separator. Maybe if we add the star as the start of expansion, we can fix this. But I will tell you straight away, this is low in priority for me as all the style guides that I follow require spaces around stars. If it affects you a lot, I could review a PR on that.
