### ISSUE TITLE
How to configure for template implementation?

### ISSUE THREAD

**Issue by NeatNit** [niosus/EasyClangComplete#658]
# System info: #
- Sublime Text version: `3.2.2`
- Which system are you on: `Linux`
- Clang version: `6.0.0`

# What happens:  #
I've gotten lost in the manual a few times trying to figure this out, and I'm nowhere closer.

I'm working on a school assignment where I have to implement a generic class. Since [templates must be implemented in header files](https://stackoverflow.com/questions/495021/why-can-templates-only-be-implemented-in-the-header-file), we are implementing it like this:

```CPP
// Foo.h
template <typename T>
class Foo
{
    void doSomething(T param);
};

#include "FooImp.h"

// FooImp.h
template <typename T>
void Foo<T>::doSomething(T param)
{
    //implementation
}
```

(this is also part of the top answer to the SO question linked above, albeit with `Foo.tpp` instead of `FooImp.h`)

The file names are required to be exactly those by the assignment. The main file I'm working in is `FooImp.h`, but by definition it must not `#include Foo.h`, so ECC spits out a lot of errors at me.

How do I configure ECC for this?

Note: since this is a school assignment I'd rather not be forced to use and learn too many tools that aren't part of the assignment (e.g. CMake), so ideally I'd just be able to tell ECC that "this particular file is actually included in that particular file" and have it work out the rest.

**Comment by niosus** [comment]
There is no way to configure ECC to deal with that and it is not an issue of the plugin. You question is much more related to understanding C++ than to this plugin itself. 

You will be able to navigate your `Foo.h` file albeit missing the completions of anything related to the template type T, and ECC won't be able to do anything in `FooImp.h`. Let me explain why.

- In `Foo.h` you have no idea what type is T, so whatever is dependent on this type will not be available to you for completion. You only know T when this template class gets used somewhere else. By design, you don't know this when editing the header file. 
- In `FooImp.h` you have no idea about the declarations of the functions you are defining as there is no include at the top of the file. I could theoretically try to guess that this file is actually an implementation but there is no single convention for naming/using such implementation files, so I don't even consider this idea seriously.

Hope that answers your question.

**Comment by NeatNit** [comment]
Thank you for the detailed answer.

> In Foo.h you have no idea what type is T, so whatever is dependent on this type will not be available to you for completion. You only know T when this template class gets used somewhere else. By design, you don't know this when editing the header file.

I understand what you're saying, but ECC can still (hopefully?) help with completions of other things, like usage of the standard library. At the very least, it can tell you about syntax errors.

> In FooImp.h you have no idea about the declarations of the functions you are defining as there is no include at the top of the file. I could theoretically implement some guessing mechanism to try to infer that a file is actually an implementation of some template declarations in some other file, but there is no single convention for naming/using such implementation files, so I don't even consider this idea seriously.

Yeah, guessing would make no sense here, but that's exactly why I asked about how to *configure* ECC to do this. Each user can tell ECC how to know which file goes where in the code. In my particular case, I can actually point to a single .cpp file which includes all the files I'm working on and contains a `main`, so if I could just configure "regardless of what file I'm editing in this project, use *that file* as the base", then it should be able to at least not throw false errors all over the place, and at most, actually have information about what T could be.

Does that make sense? Or am I still missing something big?

**Comment by niosus** [comment]
> help with completions of other things, like usage of the standard library

This should work in the `Foo.h` header file as soon as no template argument is involved.

>  just configure "regardless of what file I'm editing in this project, use that file as the base"

I'd say that while it might fit your workflow there is no general workflow like this. The best way is to either implement the template library with explicit instantiations for the types you expect in a `cpp` file or just ignore the files like `FooImp.h` in ECC.
