### ISSUE TITLE
Ninja script to guess flags

### ISSUE THREAD

**Issue by niosus** [niosus/EasyClangComplete#76]
Just as already implemented for the cmake it would be cool to use ninja build system to guess the build flags.

@rchl provided a starting point:

> I'm thinking about just exposing a setting that could be set to a script that provides compilation flags (all, including include paths, defines, other flags).
> 
> For ninja there is a script [1] that is made to be used with SublimeClang. The meat of the functionality is in another script [2] that it uses. Basically it uses ninja tools (see ninja -t list) to get compilation commands for given file path. It looks like the script is not really chromium specific so it could indeed be integrated 'natively' into the plugin.

I am moving the discussion here from #19

**Comment by rchl** [comment]
More info:

Ninja can actually generate compile commands and I believe the format is the same as with cmake. This is the command to do it:
```
ninja -C out/Release -t compdb objcxx cxx > compile_commands.json
```
But I don't think it would be feasible to generate and find that file automatically. That is because ninja's output directory can be freely chosen and (as is with the project I'm working on) it can be even buried down the directory tree or on a different drive.

IMO it would be necessary for the user to explicitly specify the output path of ninja. Ideally in project settings. Then plugin can generate and use that file.

Some notes:
 - the paths in that file can be relative to the output directory so would need to be converted to absolute.
 - For clang-cl, the arguments are passed through an `*.rsp` file so the command listed in json file just references that file instead of listing all arguments. This would be tricky to handle as that file is only generated by ninja on compiling the file and then deleted immediately. There is a way to keep those files on disk after use by using `-t keeprsp` flag with ninja but that would need to be done by the user explicitly rather than the plugin (I don't think anyone wants the plugin to compile the project on its own). And even when those files are on disk, the plugin would need to read them and get flags from them. It's a bit of work.

**Comment by niosus** [comment]
Damn, completely overlooked your comment here. Thanks for the info. I don't like adding settings that have no use-friendly default. Maybe we could interactively ask user which build system he wants to use for the project and then if it is ninja - ask for the folder and then store it in project settings.

**Comment by rchl** [comment]
Yeah, I think having an action that user would have to explicitly invoke would the correct way to do it.
But even then, the problems I've mentioned would make it difficult to handle ninja automatically from the plugin.

**Comment by niosus** [comment]
Actually, looking at ninja's website I have found this option:
> given a list of rules, each of which is expected to be a C family language compiler rule whose first input is the name of the source file, prints on standard output a compilation database in the JSON format expected by the Clang tooling interface. Available since Ninja 1.2.

Which is pretty cool, because we can use it to generate a compilation database with which we can (to some degree) work.

**Comment by rchl** [comment]
Talked about it few comments above. :)
Only tricky part is handling rsp files. Also talked about it above.

Some additional info to my comment above:
 - Generate all rsp files (does a dry-run but saves rsp files): `ninja -n -d keeprsp target_name`
 - Execute the build command that produces foo.obj: `ninja foo.obj`
 - Execute the build command that produces an obj file that has foo.cc as input: `ninja ..\foo.cc^`

**Comment by niosus** [comment]
Yeah, you are right, sorry for that :) Totally missed the part about the flag.

**Comment by niosus** [comment]
As of now, one can use a compilation database that can be produced during a ninja build. Should I close this one? I don't see a better way to handle ninja builds. Running full build just to get flags seems like an overkill to me.

**Comment by niosus** [comment]
As you now know there is no support currently (issue #115), but I think I can close this issue. I don't think ninja should be messed with from inside the plugin.
