### ISSUE TITLE
Autocomplete suggestions appear after completion popup was closed

### ISSUE THREAD

**Issue by rchl** [niosus/EasyClangComplete#81]
I'm working with a big code base and so it takes a couple of seconds to compile the code and provide suggestions. The problem is when I close autocomplete popup before results arrive.

1. Type `foo->` to trigger suggestions
2. Select any suggestion (no clang completions were added yet) and press tab to complete.

Expected:
Clang suggestion do not open the popup again when they arrive.

Actual:
Clang suggestions arrive some time later and open the suggestion popup again.

**Comment by niosus** [comment]
Yep, thanks. This one is also known to me. The problem is that there is no way to cancel the thread that is loading the suggestions once it is already running. So I see two ways.
- Start the thread with delay if the user waits for it.
- Discard the results if the user doesn't need it.

In both cases care has to be taken to not discard the results when they are still needed by the user.

**Comment by rchl** [comment]
> Start the thread with delay if the user waits for it.
Don't think that would work reliably and resolve the problem really.
> Discard the results if the user doesn't need it.
That would be preferable IMO.

**Comment by niosus** [comment]
should be fixed by @rchl 
Closing for now.

**Comment by rchl** [comment]
No, I've accidentally referenced this issue, sorry. The commit that was merged had issue number rewritten to be proper.

**Comment by niosus** [comment]
Ah, no problem. Then this one is not closed yet.

**Comment by niosus** [comment]
Should be fixed in commit 1c3657b757ca4ff7e135e31ca865ee34610d0168

Now the plugin checks a position-based hash in order to know if the completions should be shown.
